<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.120" timestamp="2024-06-13T15:38:02.611769" hostname="raphael-XPS-13-9370"><testcase classname="" name="tests.module2.test_exercise1" time="0.000"><error message="collection failure">venv/lib/python3.10/site-packages/_pytest/python.py:492: in importtestmodule
    mod = import_path(
venv/lib/python3.10/site-packages/_pytest/pathlib.py:591: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1050: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1027: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1006: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:688: in _load_unlocked
    ???
venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
tests/module2/test_exercise1.py:3: in &lt;module&gt;
    from mysupertools.tool.multiplication_a_b import multiply
E     File "/home/raphael/admin_data_science_practice/venv/lib/python3.10/site-packages/mysupertools/tool/multiplication_a_b.py", line 5
E       try:
E   IndentationError: unexpected indent</error></testcase></testsuite></testsuites>