{"is_passed_test": false, "score": "0", "logs": "venv/lib/python3.10/site-packages/_pytest/python.py:492: in importtestmodule\n    mod = import_path(\nvenv/lib/python3.10/site-packages/_pytest/pathlib.py:591: in import_path\n    importlib.import_module(module_name)\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n&lt;frozen importlib._bootstrap&gt;:1050: in _gcd_import\n    ???\n&lt;frozen importlib._bootstrap&gt;:1027: in _find_and_load\n    ???\n&lt;frozen importlib._bootstrap&gt;:1006: in _find_and_load_unlocked\n    ???\n&lt;frozen importlib._bootstrap&gt;:688: in _load_unlocked\n    ???\nvenv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:178: in exec_module\n    exec(co, module.__dict__)\ntests/module2/test_exercise1.py:3: in &lt;module&gt;\n    from mysupertools.tool.multiplication_a_b import multiply\nE     File \"/home/raphael/admin_data_science_practice/venv/lib/python3.10/site-packages/mysupertools/tool/multiplication_a_b.py\", line 5\nE       try:\nE   IndentationError: unexpected indent", "updated_time_utc": "2024-06-13T13:37:57"}
